a64multi5_encoder \
a64multi_encoder \
aac_at_decoder \
aac_at_encoder \
aac_decoder \
aac_encoder \
aac_fixed_decoder \
aac_latm_parser \
aac_mf_encoder \
aac_parser \
aandcttables \
aasc_decoder \
ac3_at_decoder \
ac3_decoder \
ac3_encoder \
ac3_fixed_decoder \
ac3_fixed_encoder \
ac3_mf_encoder \
ac3_parser \
ac3dsp \
acelp_kelvin_decoder \
adpcm_4xm_decoder \
adpcm_adx_decoder \
adpcm_adx_encoder \
adpcm_afc_decoder \
adpcm_agm_decoder \
adpcm_aica_decoder \
adpcm_argo_decoder \
adpcm_argo_encoder \
adpcm_ct_decoder \
adpcm_dtk_decoder \
adpcm_ea_decoder \
adpcm_ea_maxis_xa_decoder \
adpcm_ea_r1_decoder \
adpcm_ea_r2_decoder \
adpcm_ea_r3_decoder \
adpcm_ea_xas_decoder \
adpcm_g722_decoder \
adpcm_g722_encoder \
adpcm_g726_decoder \
adpcm_g726_encoder \
adpcm_g726le_decoder \
adpcm_g726le_encoder \
adpcm_ima_acorn_decoder \
adpcm_ima_alp_decoder \
adpcm_ima_alp_encoder \
adpcm_ima_amv_decoder \
adpcm_ima_amv_encoder \
adpcm_ima_apc_decoder \
adpcm_ima_apm_decoder \
adpcm_ima_apm_encoder \
adpcm_ima_cunning_decoder \
adpcm_ima_dat4_decoder \
adpcm_ima_dk3_decoder \
adpcm_ima_dk4_decoder \
adpcm_ima_ea_eacs_decoder \
adpcm_ima_ea_sead_decoder \
adpcm_ima_iss_decoder \
adpcm_ima_moflex_decoder \
adpcm_ima_mtf_decoder \
adpcm_ima_oki_decoder \
adpcm_ima_qt_at_decoder \
adpcm_ima_qt_decoder \
adpcm_ima_qt_encoder \
adpcm_ima_rad_decoder \
adpcm_ima_smjpeg_decoder \
adpcm_ima_ssi_decoder \
adpcm_ima_ssi_encoder \
adpcm_ima_wav_decoder \
adpcm_ima_wav_encoder \
adpcm_ima_ws_decoder \
adpcm_ima_ws_encoder \
adpcm_ms_decoder \
adpcm_ms_encoder \
adpcm_mtaf_decoder \
adpcm_psx_decoder \
adpcm_sbpro_2_decoder \
adpcm_sbpro_3_decoder \
adpcm_sbpro_4_decoder \
adpcm_swf_decoder \
adpcm_swf_encoder \
adpcm_thp_decoder \
adpcm_thp_le_decoder \
adpcm_vima_decoder \
adpcm_xa_decoder \
adpcm_xmd_decoder \
adpcm_yamaha_decoder \
adpcm_yamaha_encoder \
adpcm_zork_decoder \
adts_header \
adx_parser \
agm_decoder \
aic_decoder \
alac_at_decoder \
alac_at_encoder \
alac_decoder \
alac_encoder \
alias_pix_decoder \
alias_pix_encoder \
als_decoder \
amf \
amr_nb_at_decoder \
amr_parser \
amrnb_decoder \
amrwb_decoder \
amv_encoder \
anm_decoder \
ansi_decoder \
anull_decoder \
anull_encoder \
apac_decoder \
ape_decoder \
apng_decoder \
apng_encoder \
aptx_decoder \
aptx_encoder \
aptx_hd_decoder \
aptx_hd_encoder \
arbc_decoder \
argo_decoder \
ass_decoder \
ass_encoder \
asv1_decoder \
asv1_encoder \
asv2_decoder \
asv2_encoder \
atrac1_decoder \
atrac3_decoder \
atrac3al_decoder \
atrac3p_decoder \
atrac3pal_decoder \
atrac9_decoder \
atsc_a53 \
audio_frame_queue \
audiodsp \
aura2_decoder \
aura_decoder \
av1_amf_encoder \
av1_cuvid_decoder \
av1_d3d11va_hwaccel \
av1_d3d12va_hwaccel \
av1_decoder \
av1_dxva2_hwaccel \
av1_mediacodec_decoder \
av1_mediacodec_encoder \
av1_nvdec_hwaccel \
av1_nvenc_encoder \
av1_parser \
av1_qsv_encoder \
av1_vaapi_encoder \
av1_vaapi_hwaccel \
av1_vdpau_hwaccel \
av1_vulkan_hwaccel \
avrn_decoder \
avrp_decoder \
avrp_encoder \
avs2_parser \
avs3_parser \
avs_decoder \
avui_decoder \
avui_encoder \
ayuv_decoder \
ayuv_encoder \
bethsoftvid_decoder \
bfi_decoder \
bink_decoder \
binkaudio_dct_decoder \
binkaudio_rdft_decoder \
bintext_decoder \
bitpacked_decoder \
bitpacked_encoder \
blockdsp \
bmp_decoder \
bmp_encoder \
bmp_parser \
bmv_audio_decoder \
bmv_video_decoder \
bonk_decoder \
brender_pix_decoder \
bswapdsp \
c93_decoder \
cabac \
cavs_decoder \
cavsvideo_parser \
cbd2_decoder \
cbs \
cbs_av1 \
cbs_h264 \
cbs_h265 \
cbs_h266 \
cbs_jpeg \
cbs_mpeg2 \
cbs_vp8 \
cbs_vp9 \
ccaption_decoder \
cdgraphics_decoder \
cdtoons_decoder \
cdxl_decoder \
cfhd_decoder \
cfhd_encoder \
cinepak_decoder \
cinepak_encoder \
clearvideo_decoder \
cljr_decoder \
cljr_encoder \
cllc_decoder \
comfortnoise_decoder \
comfortnoise_encoder \
cook_decoder \
cook_parser \
cpia_decoder \
cri_decoder \
cri_parser \
cscd_decoder \
cyuv_decoder \
d3d11va \
d3d12va \
dca_decoder \
dca_encoder \
dca_parser \
dds_decoder \
deflate_wrapper \
derf_dpcm_decoder \
dfa_decoder \
dfpwm_decoder \
dfpwm_encoder \
dirac_decoder \
dirac_parser \
dnxhd_decoder \
dnxhd_encoder \
dnxhd_parser \
dolby_e_decoder \
dolby_e_parser \
dovi_rpu \
dpx_decoder \
dpx_encoder \
dpx_parser \
dsd_lsbf_decoder \
dsd_lsbf_planar_decoder \
dsd_msbf_decoder \
dsd_msbf_planar_decoder \
dsicinaudio_decoder \
dsicinvideo_decoder \
dss_sp_decoder \
dst_decoder \
dvaudio_decoder \
dvaudio_parser \
dvbsub_decoder \
dvbsub_encoder \
dvbsub_parser \
dvd_nav_parser \
dvdsub_decoder \
dvdsub_encoder \
dvdsub_parser \
dvvideo_decoder \
dvvideo_encoder \
dxa_decoder \
dxtory_decoder \
dxv_decoder \
dxv_encoder \
dxva2 \
eac3_at_decoder \
eac3_decoder \
eac3_encoder \
eacmv_decoder \
eamad_decoder \
eatgq_decoder \
eatgv_decoder \
eatqi_decoder \
eightbps_decoder \
eightsvx_exp_decoder \
eightsvx_fib_decoder \
elbg_filter \
error_resilience \
escape124_decoder \
escape130_decoder \
evc_parser \
evcparse \
evrc_decoder \
exif \
exr_decoder \
exr_encoder \
extract_extradata_bsf \
faandct \
faanidct \
fastaudio_decoder \
fdctdsp \
ffv1_decoder \
ffv1_encoder \
ffwavesynth_decoder \
fic_decoder \
fits_decoder \
fits_demuxer \
fits_encoder \
flac_decoder \
flac_encoder \
flac_parser \
flashsv2_decoder \
flashsv2_encoder \
flashsv_decoder \
flashsv_encoder \
flic_decoder \
flv_decoder \
flv_encoder \
fmtconvert \
fmvc_decoder \
fourxm_decoder \
frame_thread_encoder \
fraps_decoder \
frwu_decoder \
ftr_decoder \
ftr_parser \
g2m_decoder \
g723_1_decoder \
g723_1_encoder \
g723_1_parser \
g729_decoder \
g729_parser \
gdv_decoder \
gem_decoder \
gif_decoder \
gif_encoder \
gif_parser \
golomb \
gremlin_dpcm_decoder \
gsm_decoder \
gsm_ms_at_decoder \
gsm_ms_decoder \
gsm_parser \
h261_decoder \
h261_encoder \
h261_parser \
h263_decoder \
h263_encoder \
h263_parser \
h263_v4l2m2m_decoder \
h263_v4l2m2m_encoder \
h263_vaapi_hwaccel \
h263_videotoolbox_hwaccel \
h263dsp \
h263i_decoder \
h264_amf_encoder \
h264_cuvid_decoder \
h264_d3d11va_hwaccel \
h264_d3d12va_hwaccel \
h264_decoder \
h264_dxva2_hwaccel \
h264_mediacodec_decoder \
h264_mediacodec_encoder \
h264_metadata_bsf \
h264_mf_encoder \
h264_mmal_decoder \
h264_nvdec_hwaccel \
h264_nvenc_encoder \
h264_omx_encoder \
h264_parser \
h264_qsv_decoder \
h264_qsv_encoder \
h264_qsv_hwaccel \
h264_rkmpp_decoder \
h264_sei \
h264_v4l2m2m_decoder \
h264_v4l2m2m_encoder \
h264_vaapi_encoder \
h264_vaapi_hwaccel \
h264_vdpau_hwaccel \
h264_videotoolbox_encoder \
h264_videotoolbox_hwaccel \
h264_vulkan_hwaccel \
h264chroma \
h264dsp \
h264parse \
h264pred \
h264qpel \
hap_decoder \
hap_encoder \
hapqa_extract_bsf \
hca_decoder \
hcom_decoder \
hdr_decoder \
hdr_encoder \
hdr_parser \
hevc_amf_encoder \
hevc_cuvid_decoder \
hevc_d3d11va_hwaccel \
hevc_d3d12va_hwaccel \
hevc_decoder \
hevc_dxva2_hwaccel \
hevc_mediacodec_decoder \
hevc_mediacodec_encoder \
hevc_metadata_bsf \
hevc_mf_encoder \
hevc_nvdec_hwaccel \
hevc_nvenc_encoder \
hevc_parser \
hevc_qsv_decoder \
hevc_qsv_encoder \
hevc_qsv_hwaccel \
hevc_rkmpp_decoder \
hevc_sei \
hevc_v4l2m2m_decoder \
hevc_v4l2m2m_encoder \
hevc_vaapi_encoder \
hevc_vaapi_hwaccel \
hevc_vdpau_hwaccel \
hevc_videotoolbox_encoder \
hevc_vulkan_hwaccel \
hevcparse \
hnm4_video_decoder \
hpeldsp \
hq_hqa_decoder \
hqx_decoder \
huffman \
huffyuv_decoder \
huffyuv_encoder \
huffyuvdsp \
huffyuvencdsp \
hymt_decoder \
idcin_decoder \
idctdsp \
idf_decoder \
iff_ilbm_decoder \
iirfilter \
ilbc_at_decoder \
ilbc_at_encoder \
ilbc_decoder \
imc_decoder \
imm4_decoder \
imm5_decoder \
indeo2_decoder \
indeo3_decoder \
indeo4_decoder \
indeo5_decoder \
inflate_wrapper \
interplay_acm_decoder \
interplay_dpcm_decoder \
interplay_video_decoder \
intrax8 \
ipu_decoder \
ipu_parser \
ividsp \
jacosub_decoder \
jni \
jpeg2000_decoder \
jpeg2000_encoder \
jpeg2000_parser \
jpegls_decoder \
jpegls_encoder \
jpegtables \
jpegxl_parser \
jv_decoder \
kgv1_decoder \
kmvc_decoder \
lagarith_decoder \
lcms2 \
lead_decoder \
libaom_av1_decoder \
libaom_av1_encoder \
libaribb24_decoder \
libaribcaption_decoder \
libcelt_decoder \
libcodec2_decoder \
libcodec2_encoder \
libdav1d_decoder \
libdavs2_decoder \
libfdk_aac_decoder \
libfdk_aac_encoder \
libgsm_decoder \
libgsm_encoder \
libgsm_ms_decoder \
libgsm_ms_encoder \
libilbc_decoder \
libilbc_encoder \
libjxl_decoder \
libjxl_encoder \
libkvazaar_encoder \
libmp3lame_encoder \
libopencore_amrnb_decoder \
libopencore_amrnb_encoder \
libopencore_amrwb_decoder \
libopenh264_decoder \
libopenh264_encoder \
libopenjpeg_encoder \
libopus_decoder \
libopus_encoder \
librav1e_encoder \
librsvg_decoder \
libshine_encoder \
libspeex_decoder \
libspeex_encoder \
libsvtav1_encoder \
libtheora_encoder \
libtwolame_encoder \
libuavs3d_decoder \
libvo_amrwbenc_encoder \
libvorbis_decoder \
libvorbis_encoder \
libvpx_vp8_decoder \
libvpx_vp8_encoder \
libvpx_vp9_decoder \
libvpx_vp9_encoder \
libwebp_anim_encoder \
libwebp_encoder \
libx262_encoder \
libx264_encoder \
libx265_encoder \
libxavs2_encoder \
libxavs_encoder \
libxevd_decoder \
libxeve_encoder \
libxvid_encoder \
libzvbi_teletext_decoder \
ljpeg_encoder \
llauddsp \
llviddsp \
llvidencdsp \
loco_decoder \
lpc \
lscr_decoder \
lsp \
lzf \
m101_decoder \
mace3_decoder \
mace6_decoder \
magicyuv_decoder \
magicyuv_encoder \
mdec_decoder \
me_cmp \
media100_decoder \
mediacodec \
metasound_decoder \
microdvd_decoder \
mimic_decoder \
misc4_decoder \
misc4_parser \
mjpeg_cuvid_decoder \
mjpeg_decoder \
mjpeg_encoder \
mjpeg_nvdec_hwaccel \
mjpeg_parser \
mjpeg_qsv_decoder \
mjpeg_qsv_encoder \
mjpeg_vaapi_encoder \
mjpeg_vaapi_hwaccel \
mjpegb_decoder \
mlp_decoder \
mlp_encoder \
mlp_parser \
mmvideo_decoder \
mobiclip_decoder \
motionpixels_decoder \
movtext_decoder \
movtext_encoder \
mp1_at_decoder \
mp1_decoder \
mp1float_decoder \
mp2_at_decoder \
mp2_decoder \
mp2_encoder \
mp2fixed_encoder \
mp2float_decoder \
mp3_at_decoder \
mp3_decoder \
mp3_mf_encoder \
mp3adu_decoder \
mp3adufloat_decoder \
mp3float_decoder \
mp3on4_decoder \
mp3on4float_decoder \
mpc7_decoder \
mpc8_decoder \
mpeg1_cuvid_decoder \
mpeg1_nvdec_hwaccel \
mpeg1_v4l2m2m_decoder \
mpeg1_vdpau_hwaccel \
mpeg1_videotoolbox_hwaccel \
mpeg1video_decoder \
mpeg1video_encoder \
mpeg2_cuvid_decoder \
mpeg2_d3d11va_hwaccel \
mpeg2_d3d12va_hwaccel \
mpeg2_dxva2_hwaccel \
mpeg2_mediacodec_decoder \
mpeg2_mmal_decoder \
mpeg2_nvdec_hwaccel \
mpeg2_qsv_decoder \
mpeg2_qsv_encoder \
mpeg2_qsv_hwaccel \
mpeg2_v4l2m2m_decoder \
mpeg2_vaapi_encoder \
mpeg2_vaapi_hwaccel \
mpeg2_vdpau_hwaccel \
mpeg2_videotoolbox_hwaccel \
mpeg2video_decoder \
mpeg2video_encoder \
mpeg4_cuvid_decoder \
mpeg4_decoder \
mpeg4_encoder \
mpeg4_mediacodec_decoder \
mpeg4_mediacodec_encoder \
mpeg4_nvdec_hwaccel \
mpeg4_omx_encoder \
mpeg4_v4l2m2m_decoder \
mpeg4_v4l2m2m_encoder \
mpeg4_vaapi_hwaccel \
mpeg4_vdpau_hwaccel \
mpeg4_videotoolbox_hwaccel \
mpeg4audio \
mpeg4video_parser \
mpeg_er \
mpegaudio \
mpegaudio_parser \
mpegaudiodsp \
mpegaudioheader \
mpegvideo \
mpegvideo_decoder \
mpegvideo_parser \
mpegvideodec \
mpegvideoenc \
mpl2_decoder \
msa1_decoder \
mscc_decoder \
msmpeg4dec \
msmpeg4enc \
msnsiren_decoder \
msp2_decoder \
msrle_decoder \
msrle_encoder \
mss1_decoder \
mss2_decoder \
mss34dsp \
msvideo1_decoder \
msvideo1_encoder \
mszh_decoder \
mts2_decoder \
mv30_decoder \
mvc1_decoder \
mvc2_decoder \
mvdv_decoder \
mvha_decoder \
mwsc_decoder \
mxpeg_decoder \
nellymoser_decoder \
nellymoser_encoder \
notchlc_decoder \
nuv_decoder \
nvdec \
on2avc_decoder \
opus_decoder \
opus_encoder \
opus_parser \
osq_decoder \
paf_audio_decoder \
paf_video_decoder \
pam_decoder \
pam_encoder \
pbm_decoder \
pbm_encoder \
pcm_alaw_at_decoder \
pcm_alaw_at_encoder \
pcm_alaw_decoder \
pcm_alaw_encoder \
pcm_bluray_decoder \
pcm_bluray_encoder \
pcm_dvd_decoder \
pcm_dvd_encoder \
pcm_f16le_decoder \
pcm_f24le_decoder \
pcm_f32be_decoder \
pcm_f32be_encoder \
pcm_f32le_decoder \
pcm_f32le_encoder \
pcm_f64be_decoder \
pcm_f64be_encoder \
pcm_f64le_decoder \
pcm_f64le_encoder \
pcm_lxf_decoder \
pcm_mulaw_at_decoder \
pcm_mulaw_at_encoder \
pcm_mulaw_decoder \
pcm_mulaw_encoder \
pcm_s8_decoder \
pcm_s8_encoder \
pcm_s8_planar_decoder \
pcm_s8_planar_encoder \
pcm_s16be_decoder \
pcm_s16be_encoder \
pcm_s16be_planar_decoder \
pcm_s16be_planar_encoder \
pcm_s16le_decoder \
pcm_s16le_encoder \
pcm_s16le_planar_decoder \
pcm_s16le_planar_encoder \
pcm_s24be_decoder \
pcm_s24be_encoder \
pcm_s24daud_decoder \
pcm_s24daud_encoder \
pcm_s24le_decoder \
pcm_s24le_encoder \
pcm_s24le_planar_decoder \
pcm_s24le_planar_encoder \
pcm_s32be_decoder \
pcm_s32be_encoder \
pcm_s32le_decoder \
pcm_s32le_encoder \
pcm_s32le_planar_decoder \
pcm_s32le_planar_encoder \
pcm_s64be_decoder \
pcm_s64be_encoder \
pcm_s64le_decoder \
pcm_s64le_encoder \
pcm_sga_decoder \
pcm_u8_decoder \
pcm_u8_encoder \
pcm_u16be_decoder \
pcm_u16be_encoder \
pcm_u16le_decoder \
pcm_u16le_encoder \
pcm_u24be_decoder \
pcm_u24be_encoder \
pcm_u24le_decoder \
pcm_u24le_encoder \
pcm_u32be_decoder \
pcm_u32be_encoder \
pcm_u32le_decoder \
pcm_u32le_encoder \
pcm_vidc_decoder \
pcm_vidc_encoder \
pcx_decoder \
pcx_encoder \
pdv_decoder \
pfm_decoder \
pfm_encoder \
pgm_decoder \
pgm_encoder \
pgmyuv_decoder \
pgmyuv_encoder \
pgssub_decoder \
pgx_decoder \
phm_decoder \
phm_encoder \
photocd_decoder \
pictor_decoder \
pixblockdsp \
pixlet_decoder \
pjs_decoder \
png_decoder \
png_encoder \
png_parser \
pnm_parser \
ppm_decoder \
ppm_encoder \
prores_aw_encoder \
prores_decoder \
prores_encoder \
prores_ks_encoder \
prores_videotoolbox_encoder \
prosumer_decoder \
psd_decoder \
ptx_decoder \
qcelp_decoder \
qdm2_at_decoder \
qdm2_decoder \
qdmc_at_decoder \
qdmc_decoder \
qdraw_decoder \
qoa_decoder \
qoi_decoder \
qoi_encoder \
qoi_parser \
qpeg_decoder \
qpeldsp \
qsv \
qsvdec \
qsvenc \
qtrle_decoder \
qtrle_encoder \
r10k_decoder \
r10k_encoder \
r210_decoder \
r210_encoder \
ra_144_decoder \
ra_144_encoder \
ra_288_decoder \
ralf_decoder \
rangecoder \
rasc_decoder \
rawvideo_decoder \
rawvideo_encoder \
realtext_decoder \
remove_extradata_bsf \
rka_decoder \
rl2_decoder \
roq_decoder \
roq_dpcm_decoder \
roq_dpcm_encoder \
roq_encoder \
rpza_decoder \
rpza_encoder \
rscc_decoder \
rtv1_decoder \
rv10_decoder \
rv10_encoder \
rv20_decoder \
rv20_encoder \
rv30_decoder \
rv34_parser \
rv34dsp \
rv40_decoder \
s302m_decoder \
s302m_encoder \
sami_decoder \
sanm_decoder \
sbc_decoder \
sbc_encoder \
sbc_parser \
scpr_decoder \
screenpresso_decoder \
sdx2_dpcm_decoder \
sga_decoder \
sgi_decoder \
sgi_encoder \
sgirle_decoder \
sheervideo_decoder \
shorten_decoder \
simbiosis_imx_decoder \
sinewin \
sipr_decoder \
sipr_parser \
siren_decoder \
smackaud_decoder \
smacker_decoder \
smc_decoder \
smc_encoder \
snappy \
snow_decoder \
snow_encoder \
sol_dpcm_decoder \
sonic_decoder \
sonic_encoder \
sonic_ls_encoder \
sp5x_decoder \
speedhq_decoder \
speedhq_encoder \
speex_decoder \
srgc_decoder \
srt_decoder \
srt_encoder \
ssa_decoder \
ssa_encoder \
startcode \
stl_decoder \
subrip_decoder \
subrip_encoder \
subviewer1_decoder \
subviewer_decoder \
sunrast_decoder \
sunrast_encoder \
svq1_decoder \
svq1_encoder \
svq3_decoder \
tak_decoder \
tak_demuxer \
tak_parser \
targa_decoder \
targa_encoder \
targa_y216_decoder \
tdsc_decoder \
text_decoder \
text_encoder \
texturedsp \
texturedspenc \
tiertexseqvideo_decoder \
tiff_decoder \
tiff_encoder \
tmv_decoder \
tpeldsp \
truehd_core_bsf \
truehd_decoder \
truehd_encoder \
truemotion1_decoder \
truemotion2_decoder \
truemotion2rt_decoder \
truespeech_decoder \
tscc2_decoder \
tscc_decoder \
tta_decoder \
tta_encoder \
ttml_encoder \
twinvq_decoder \
txd_decoder \
ulti_decoder \
utvideo_decoder \
utvideo_encoder \
v4l2_m2m \
v210_decoder \
v210_encoder \
v210x_decoder \
v308_decoder \
v308_encoder \
v408_decoder \
v408_encoder \
v410_decoder \
v410_encoder \
vaapi \
vaapi_encode \
vb_decoder \
vble_decoder \
vbn_decoder \
vbn_encoder \
vc1_cuvid_decoder \
vc1_d3d11va_hwaccel \
vc1_d3d12va_hwaccel \
vc1_decoder \
vc1_dxva2_hwaccel \
vc1_mmal_decoder \
vc1_nvdec_hwaccel \
vc1_parser \
vc1_qsv_decoder \
vc1_qsv_hwaccel \
vc1_v4l2m2m_decoder \
vc1_vaapi_hwaccel \
vc1_vdpau_hwaccel \
vc1dsp \
vc2_encoder \
vcr1_decoder \
vdpau \
videodsp \
videotoolbox \
vmdaudio_decoder \
vmdvideo_decoder \
vmix_decoder \
vmnc_decoder \
vnull_decoder \
vnull_encoder \
vorbis_decoder \
vorbis_encoder \
vp3_decoder \
vp3_parser \
vp3dsp \
vp5_decoder \
vp6_decoder \
vp7_decoder \
vp8_cuvid_decoder \
vp8_decoder \
vp8_mediacodec_decoder \
vp8_mediacodec_encoder \
vp8_nvdec_hwaccel \
vp8_parser \
vp8_qsv_decoder \
vp8_qsv_hwaccel \
vp8_rkmpp_decoder \
vp8_v4l2m2m_decoder \
vp8_v4l2m2m_encoder \
vp8_vaapi_encoder \
vp8_vaapi_hwaccel \
vp8dsp \
vp9_cuvid_decoder \
vp9_d3d11va_hwaccel \
vp9_d3d12va_hwaccel \
vp9_decoder \
vp9_dxva2_hwaccel \
vp9_mediacodec_decoder \
vp9_mediacodec_encoder \
vp9_nvdec_hwaccel \
vp9_parser \
vp9_qsv_encoder \
vp9_rkmpp_decoder \
vp9_v4l2m2m_decoder \
vp9_vaapi_encoder \
vp9_vaapi_hwaccel \
vp9_vdpau_hwaccel \
vp9_videotoolbox_hwaccel \
vp56dsp \
vplayer_decoder \
vqa_decoder \
vqc_decoder \
vulkan \
vvc_parser \
wady_dpcm_decoder \
wavarc_decoder \
wavpack_decoder \
wavpack_encoder \
wbmp_decoder \
wbmp_encoder \
wcmv_decoder \
webp_decoder \
webp_parser \
webvtt_decoder \
webvtt_encoder \
wma_freqs \
wmalossless_decoder \
wmapro_decoder \
wmav1_decoder \
wmav1_encoder \
wmav2_decoder \
wmav2_encoder \
wmavoice_decoder \
wmv2_decoder \
wmv2_encoder \
wmv2dsp \
wnv1_decoder \
wrapped_avframe_decoder \
wrapped_avframe_encoder \
ws_snd1_decoder \
xan_dpcm_decoder \
xan_wc3_decoder \
xan_wc4_decoder \
xbin_decoder \
xbm_decoder \
xbm_encoder \
xbm_parser \
xface_decoder \
xface_encoder \
xl_decoder \
xma1_decoder \
xma2_decoder \
xma_parser \
xpm_decoder \
xsub_decoder \
xsub_encoder \
xwd_decoder \
xwd_encoder \
xwd_parser \
y41p_decoder \
y41p_encoder \
ylc_decoder \
yop_decoder \
yuv4_decoder \
yuv4_encoder \
zero12v_decoder \
zerocodec_decoder \
zlib_decoder \
zlib_encoder \
zmbv_decoder \
zmbv_encoder \
avformat \
flv_muxer \
hls_demuxer \
image_jpegxl_pipe_demuxer \
iso_media \
jni \
jpegxl_anim_demuxer \
matroska_demuxer \
mov_demuxer \
mp3_muxer \
mxf_muxer \
nut_muxer \
rtp_muxer \
rtpdec \
spdif_muxer
