using autoconf

intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.

import config = libconfig%lib{config}
impl_libs += $config
import intf_libs += \
  libavutil%lib{avutil} \
  libswscale%lib{swscale}

cpu = [string] $c.target.cpu
tgt_win32 = [bool] ($c.target.system == 'win32-msvc')
tgt_macos = [bool] ($c.target.system == 'darwin')

lib{swresample}: libul{swresample}: \
              libswresample/h{**} \
              $impl_libs $intf_libs

conditional_src  = $json.load($src_base/files.json)

# conditional source & assembly
import [once] libconfig%buildfile{conditional-src}
import [once] libconfig%buildfile{symbol-importation}
libul{swresample}: impl_target{symbol-importation}: libswresample/h{**}
libua{swresample}: libswresample/impl_target{conditional-asm-obja}: libswresample/asm{**}
libus{swresample}: libswresample/impl_target{conditional-asm-objs}: libswresample/asm{**}
libul{swresample}: libswresample/impl_target{conditional-src}: libswresample/c{**}

# these c files are included, not built.
libul{swresample}: libswresample/c{**_template noise_shaping_data}: include = adhoc
for t: libswresample/c{**_template noise_shaping_data}
{
  $t:
  {{
    diag copy $>
    o = $path($>)
    s = "$src_base/$path.relative($o, $out_base)"
    cp $s $o
  }}
}

# Build options.
#
import [once] libconfig%buildfile{common-configs}

out_pfx = [dir_path] $out_root/src/
src_pfx = [dir_path] $src_root/src/

c.poptions += "-I$out_pfx" "-I$src_pfx" -DBUILDING_swresample -Dav_export_libswresample=

# System libraries
sys_libs =
switch $c.target.class, $c.target.system
{
  case 'windows', 'win32-msvc'
    sys_libs += bcrypt.lib
  case 'windows', 'mingw32'
    sys_libs += -lbcrypt
}
c.libs += $sys_libs

switch ($c.target.system)
{
  case 'win32-msvc'
  {
    c.coptions += -wd4003 -wd4018 -wd4146 -wd4244 -wd4305 -wd4554 -wd4133 -wd4333
    c.poptions += -DWIN32_LEAN_AND_MEAN -D_USE_MATH_DEFINES -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_WARNINGS
  }
}

libs{swresample}: def{swresample}: include = ($c.target.system == 'win32-msvc')
def{swresample}: libul{swresample}

if ($c.target.system == 'mingw32')
  c.loptions += -Wl,--export-all-symbols

# Export options.
#
lib{swresample}:
{
  c.export.poptions = "-I$out_pfx" "-I$src_pfx" -Dav_export_libswresample=
  c.export.libs = $intf_libs $sys_libs
}

if ($c.target.system == 'win32-msvc')
{
  libs{swresample}:
  {
    c.export.poptions += -Dav_export_libswresample=__declspec\(dllimport\)
  }
}

# For pre-releases use the complete version to make sure they cannot
# be used in place of another pre-release or the final version. See
# the version module for details on the version.* variable values.
#
if $version.pre_release
  lib{swresample}: bin.lib.version = "-$version.project_id"
else
  lib{swresample}: bin.lib.version = "-$version.major.$version.minor"

# Install recreating subdirectories.
#
h{*}:
{
  install         = include/
  install.subdirs = true
}
