using autoconf

intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.

import config = libconfig%lib{config}
impl_libs += $config
import intf_libs += \
  libavutil%liba{avutil} \
  libavcodec%liba{avcodec} \
  libswscale%liba{swscale} \
  libswresample%liba{swresample}

cpu = [string] $c.target.cpu
tgt_win32 = [bool] ($c.target.system == 'win32-msvc')
tgt_macos = [bool] ($c.target.system == 'darwin')

lib{avformat}: libul{avformat}: libavformat/h{**} $impl_libs $intf_libs

# conditional source & assembly
import [once] libconfig%buildfile{conditional-src}
import [once] libconfig%buildfile{conditional-src}
import config_h = libconfig%h{autoconf}
import config_asm = libconfig%file{config.asm}

[rule_hint=c] \
libul{avformat-meta}: $impl_libs $intf_libs $config_asm
file{enabled_defines}: $config_h: update = match
libua{avformat}: enabled_source{avformat}: file{enabled_defines} libua{avformat-meta} json{files.json} \
                                       $config_h $config_asm libavformat/h{**}: \
                                       update = match

# these c files are included, not built.
libul{avcodec}: adhoc_source{avcodec}: include = adhoc
adhoc_source{avcodec}: libavformat/c{**_template}

libul{avformat}: libavformat/c{ \
                  protocol_list \
                  demuxer_list \
                  muxer_list \
                }: include = adhoc

libavformat/c{protocol_list}: libavformat/c{protocols} file{enabled_defines}
{{
  diag generate $>

  s = $path($<[0])     # Source file.
  f = $path($>)        # Target file.
  cat $path($<[1]) | set -w enabled_defines [string_set]

  sed -n -e 's/.*extern.* URLProtocol\s+ff_(\S+)_protocol;/\1_protocol/p' $s | set -n func_list
  if $empty($func_list)
    echo "No protocol functions found"
    exit 1
  end
  echo 'static const URLProtocol* const url_protocols[] = {' > $f
  for c: $func_list
    group = $string.ucase(CONFIG_$c)
    if ($enabled_defines[$group])
      echo $c
      echo "    &ff_$c," >> $path($>)
    end
  end
  echo "    NULL };" >> $path($>)
}}

libavformat/c{demuxer_list}: libavformat/c{allformats} file{enabled_defines}
{{
  diag generate $>

  s = $path($<[0])     # Source file.
  f = $path($>)        # Target file.
  cat $path($<[1]) | set -w enabled_defines [string_set]

                # extern const FFInputFormat  ff_ac3_demuxer;

  sed -n -e 's/^\s*extern.*FFInputFormat\s+ff_(\S*)_demuxer;/\1_demuxer/p' $s | set -n func_list
  if $empty($func_list)
    echo "No demuxer functions found"
    exit 1
  end
  echo 'static const FFInputFormat* const demuxer_list[] = {' > $f
  for c: $func_list
    group = $string.ucase(CONFIG_$c)
    if ($enabled_defines[$group])
      echo "    &ff_$c," >> $path($>)
    end
  end
  echo "    NULL };" >> $path($>)
}}

libavformat/c{muxer_list}: libavformat/c{allformats} file{enabled_defines}
{{
  diag generate $>

  s = $path($<[0])     # Source file.
  f = $path($>)        # Target file.
  cat $path($<[1]) | set -w enabled_defines [string_set]

  sed -n -e 's/^\s*extern.*FFOutputFormat\s+ff_(\S*)_muxer;/\1_muxer/p' $s | set -n func_list
  if $empty($func_list)
    echo "No muxer functions found"
    exit 1
  end
  echo 'static const FFOutputFormat* const muxer_list[] = {' > $f
  for c: $func_list
    group = $string.ucase(CONFIG_$c)
    if ($enabled_defines[$group])
      echo "    &ff_$c," >> $path($>)
    end
  end
  echo "    NULL };" >> $path($>)
}}

# Build options.
#
import [once] libconfig%buildfile{common-configs}

out_pfx = [dir_path] $out_root/src/
src_pfx = [dir_path] $src_root/src/

c.poptions += "-I$out_pfx" "-I$src_pfx" -DBUILDING_avformat -Dav_export_libavformat=

# System libraries
sys_libs =
switch $c.target.class, $c.target.system
{
  case 'windows', 'win32-msvc'
    sys_libs += bcrypt.lib
  case 'windows', 'mingw32'
    sys_libs += -lbcrypt
  case 'macos'
    sys_libs += -lc
}
c.libs += $sys_libs

switch ($c.id)
{
  case 'msvc'
  {
    c.coptions += -wd4003 -wd4018 -wd4146 -wd4244 -wd4305 -wd4554 -wd4133 -wd4333
    c.poptions += -DWIN32_LEAN_AND_MEAN -D_USE_MATH_DEFINES -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_WARNINGS
  }
}

libs{avformat}: def{avformat}: include = ($c.target.system == 'win32-msvc')
def{avformat}: libul{avformat}

if ($c.target.system == 'mingw32')
  c.loptions += -Wl,--export-all-symbols

# Export options.
#
lib{avformat}:
{
  c.export.poptions = "-I$out_pfx" "-I$src_pfx"
  c.export.libs = $intf_libs $sys_libs
}

if ($c.target.system == 'win32-msvc')
{
  liba{avformat}:
  {
    c.export.poptions += -Dav_export_libavformat=
  }
  libs{avformat}:
  {
    c.export.poptions += -Dav_export_libavformat=__declspec\(dllimport\)
  }
}
else
{
  lib{avformat}:
  {
    c.export.poptions += -Dav_export_libavformat=
  }
}

# For pre-releases use the complete version to make sure they cannot
# be used in place of another pre-release or the final version. See
# the version module for details on the version.* variable values.
#
if $version.pre_release
  lib{avformat}: bin.lib.version = "-$version.project_id"
else
  lib{avformat}: bin.lib.version = "-$version.major.$version.minor"

# Install recreating subdirectories.
#
h{*}:
{
  install         = include/
  install.subdirs = true
}
