import config = libconfig%lib{config}
import libs = \
  libswresample%lib{swresample} \
  $config

requirements = [string_set] \
  '{"timefilter": "alsa_indev"}'

# need upstream/tests/checkasm/ lib that conditionally builds the asm files.
for t : tests/c{*.c}
{
  n = [string] $name($t)
  e = [bool] true
  for str: [string_set] $requirements
  {
    pair = [json] $json.parse($str)
    k = [string] $member_name($pair)
    if ($k == $n)
    {
      s = [string] "$member_value($pair)"
      v = [strings] $regex.split($s, ' ', ' ')
      for r: [strings] ($v)
      {
        c = $($config: libavutil.$r)
        if($c != 1)
        {
          e = false
        }
      }
      if(!$e)
      {
        text "skip test: libswresample/tests/$n.$extension($t) \(requires: $s\)"
      }
    }
  }

  exe{test-$n}: $t $libs
  ./: exe{test-$n}: include = $e
}
