using autoconf

intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.

import config = libconfig%lib{config}
impl_libs += $config
import intf_libs += \
  libavutil%lib{avutil} \
  libavcodec%lib{avcodec} \
  libavformat%lib{avformat} \
  libswscale%lib{swscale} \
  libswresample%lib{swresample}

cpu = [string] $c.target.cpu
tgt_win32 = [bool] ($c.target.system == 'win32-msvc')
tgt_macos = [bool] ($c.target.system == 'darwin')

lib{avfilter}: libul{avfilter}: \
              libavfilter/h{**} \
              $impl_libs $intf_libs

conditional_src  = $json.load($src_base/files.json)

# conditional source & assembly
import [once] libconfig%buildfile{conditional-src}
import [once] libconfig%buildfile{symbol-importation}
libul{avfilter}: impl_target{symbol-importation}: libavfilter/h{**}
libua{avfilter}: libavfilter/impl_target{conditional-asm-obja}: libavfilter/asm{**}
libus{avfilter}: libavfilter/impl_target{conditional-asm-objs}: libavfilter/asm{**}
libul{avfilter}: libavfilter/impl_target{conditional-src}: libavfilter/c{**}

libul{avfilter}: libavfilter/c{ \
                  filter_list \
                }: include = adhoc

libavfilter/c{filter_list}: libavfilter/c{allfilters} file{enabled_groups}
{{
  diag generate ($>)

  s = $path($<[0])     # Source file.
  f = $path($>)        # Target file.
  cat $path($<[1]) | set -w enabled_groups [string_set]
  pattern = "AVFilter"
  thing = "parser"
  struct_name = "AVFilter"
  name = "filter_list"

  sed -n -e "s/^extern const AVFilter ff_[avfsinkrc]\{2,5\}_\([[:alnum:]_]\{1,\}\);/\1_filter/p" $s | set -n filter_LIST
  # assert ($size($filter_LIST) > 0)
  echo "static const $struct_name * const $name[] = {" > $f
  for c: $filter_LIST
    group = $string.ucase(CONFIG_$c)
    if ($enabled_groups[$group])
      echo "    &ff_$c," >> $path($>)
    end
  end
  echo "    NULL };" >> $path($>)
}}
# Build options.
#
import [once] libconfig%buildfile{common-configs}

out_pfx = [dir_path] $out_root/src/
src_pfx = [dir_path] $src_root/src/

c.poptions += "-I$out_pfx" "-I$src_pfx" -DBUILDING_avfilter -Dav_export_libavfilter=

# System libraries
sys_libs =
switch $c.target.class, $c.target.system
{
  case 'windows', 'win32-msvc'
    sys_libs += bcrypt.lib
  case 'windows', 'mingw32'
    sys_libs += -lbcrypt
}
c.libs += $sys_libs

switch ($c.target.system)
{
  case 'win32-msvc'
  {
    c.coptions += -wd4003 -wd4018 -wd4146 -wd4244 -wd4305 -wd4554 -wd4133 -wd4333
    c.poptions += -DWIN32_LEAN_AND_MEAN -D_USE_MATH_DEFINES -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_WARNINGS
  }
}

libs{avfilter}: def{avfilter}: include = ($c.target.system == 'win32-msvc')
def{avfilter}: libul{avfilter}

if ($c.target.system == 'mingw32')
  c.loptions += -Wl,--export-all-symbols

# Export options.
#
lib{avfilter}:
{
  c.export.poptions = "-I$out_pfx" "-I$src_pfx"
  c.export.libs = $intf_libs $sys_libs
}

if ($c.target.system == 'win32-msvc')
{
  liba{avfilter}:
  {
    c.export.poptions += -Dav_export_libavfilter=
  }
  libs{avfilter}:
  {
    c.export.poptions += -Dav_export_libavfilter=__declspec\(dllimport\)
  }
}
else
{
  lib{avfilter}:
  {
    c.export.poptions += -Dav_export_libavfilter=
  }
}

# For pre-releases use the complete version to make sure they cannot
# be used in place of another pre-release or the final version. See
# the version module for details on the version.* variable values.
#
if $version.pre_release
  lib{avfilter}: bin.lib.version = "-$version.project_id"
else
  lib{avfilter}: bin.lib.version = "-$version.major.$version.minor"

# Install recreating subdirectories.
#
h{*}:
{
  install         = include/
  install.subdirs = true
}
