using autoconf

intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.

import config = libconfig%lib{config}
impl_libs += $config
import intf_libs += \
  libavutil%lib{avutil} \
  libavcodec%lib{avcodec} \
  libavformat%lib{avformat} \
  libswscale%lib{swscale} \
  libswresample%lib{swresample}

cpu = [string] $c.target.cpu
tgt_win32 = [bool] ($c.target.system == 'win32-msvc')
tgt_macos = [bool] ($c.target.system == 'darwin')

lib{avfilter}: libul{avfilter}: \
              libavfilter/h{**} \
              $impl_libs $intf_libs

conditional_src  = $json.load($src_base/files.json)

# conditional source & assembly
import [once] libconfig%buildfile{conditional-src}
libua{avfilter}: libavfilter/impl_target{conditional-asm-obja}
libus{avfilter}: libavfilter/impl_target{conditional-asm-objs}
libul{avfilter}: libavfilter/impl_target{conditional-src}
libul{avfilter}: libavfilter/file{patch_exports.d}:
{
  include = $tgt_win32
  update = match
}

libul{avfilter}: libavfilter/c{ \
                  filter_list \
                }: include = adhoc

libavfilter/file{patch_exports.d}: libavfilter/h{**}
{{
  o = [dir_path] $directory($>)
  all_headers = [paths] $path($<)

  HDRS = [paths] $o/vf_nlmeans.h
  for hdr: [paths] $all_headers
    sed -n -e 's|^(extern .* [\S]*;)$|\1|gp' $hdr | set has_export
    if (!$empty($has_export))
      HDRS += [paths] $hdr
    end
  end

  diag patch $>

  # fix symbol importation on MSVC of global variables
  echo >$path($>)
  for hdr: [paths] ($HDRS)
    echo "      $path.relative($hdr, $src_base)"
    echo $hdr >>$path($>)
    # insert 'av_export_avfilter' before any global and explicitly 'extern' variables
    if ($path.leaf($hdr) == 'vf_nlmeans.h')
      sed -i -e 's|^(void ff_nlmeans_init_aarch64\(.*\);)$|av_export_avfilter \1|gp' $hdr
      sed -i -e 's|^(void ff_nlmeans_init_x86\(.*\);)$|av_export_avfilter \1|gp' $hdr
    else
      sed -i -e 's|^(extern .* [\S]*;)$|av_export_avfilter \1|gp' $hdr
    end
  end
}}

libavfilter/c{filter_list}: libavfilter/c{allfilters} file{enabled_groups}
{{
  diag generate ($>)

  s = $path($<[0])     # Source file.
  f = $path($>)        # Target file.
  cat $path($<[1]) | set -w enabled_groups [string_set]
  pattern = "AVFilter"
  thing = "parser"
  struct_name = "AVFilter"
  name = "filter_list"

  sed -n -e "s/^extern const AVFilter ff_[avfsinkrc]\{2,5\}_\([[:alnum:]_]\{1,\}\);/\1_filter/p" $s | set -n filter_LIST
  # assert ($size($filter_LIST) > 0)
  echo "static const $struct_name * const $name[] = {" > $f
  for c: $filter_LIST
    group = $string.ucase(CONFIG_$c)
    if ($enabled_groups[$group])
      echo "    &ff_$c," >> $path($>)
    end
  end
  echo "    NULL };" >> $path($>)
}}
# Build options.
#
import [once] libconfig%buildfile{common-configs}

out_pfx = [dir_path] $out_root/src/
src_pfx = [dir_path] $src_root/src/

c.poptions += "-I$out_pfx" "-I$src_pfx" -DBUILDING_avfilter -Dav_export_avfilter=

# System libraries
sys_libs =
switch $c.target.class, $c.target.system
{
  case 'windows', 'win32-msvc'
    sys_libs += bcrypt.lib
  case 'windows', 'mingw32'
    sys_libs += -lbcrypt
}
c.libs += $sys_libs

switch ($c.target.system)
{
  case 'win32-msvc'
  {
    c.coptions += -wd4003 -wd4018 -wd4146 -wd4244 -wd4305 -wd4554 -wd4133 -wd4333
    c.poptions += -DWIN32_LEAN_AND_MEAN -D_USE_MATH_DEFINES -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_WARNINGS
  }
}

libs{avfilter}: def{avfilter}: include = ($c.target.system == 'win32-msvc')
def{avfilter}: libul{avfilter}

if ($c.target.system == 'mingw32')
  c.loptions += -Wl,--export-all-symbols

# Export options.
#
lib{avfilter}:
{
  c.export.poptions = "-I$out_pfx" "-I$src_pfx"
  c.export.libs = $intf_libs $sys_libs
}

liba{avfilter}:
{
  c.export.poptions += -Dav_export_avfilter=
}

if ($c.target.system == 'win32-msvc')
{
  libs{avfilter}:
  {
    c.export.poptions += -Dav_export_avfilter=__declspec\(dllimport\)
  }
}

# For pre-releases use the complete version to make sure they cannot
# be used in place of another pre-release or the final version. See
# the version module for details on the version.* variable values.
#
if $version.pre_release
  lib{avfilter}: bin.lib.version = "-$version.project_id"
else
  lib{avfilter}: bin.lib.version = "-$version.major.$version.minor"

# Install recreating subdirectories.
#
h{*}:
{
  install         = include/
  install.subdirs = true
}
