import config = libconfig%lib{config}
import libs = \
  libavutil%lib{avutil} \
  $config

requirements = [string_set] \
  '{"pixelutils": "pixelutils"}'

# need upstream/tests/checkasm/ lib that conditionally builds the asm files.
# AFAICT test-file is disabled upstream, but it works for all but
# windows so lets be selective.
for t : tests/c{*.c -lzo -file}
{
  n = [string] $name($t)
  e = [bool] true
  for str: [string_set] $requirements
  {
    pair = [json] $json.parse($str)
    k = [string] $member_name($pair)
    if ($k == $n)
    {
      s = [string] "$member_value($pair)"
      v = [strings] $regex.split($s, ' ', ' ')
      for r: [strings] ($v)
      {
        c = $($config: libconfig.$r)
        if($c == [null] || !$c)
        {
          e = false
        }
      }
      if(!$e)
      {
        text "skip test: libavutil/tests/$n.$extension($t) \(requires: $s\)"
      }
    }
  }

  exe{test-$n}: $t $libs testscript
  {
    cwd = [path] $path.posix_representation($src_base/tests/)
  }
  ./: exe{test-$n}: include = $e
}

## Build options.
#
import [once] libconfig%buildfile{common-configs}

# needs some (any) file as input
exe{test-utf8}: test.arguments = $path.posix_string($src_base/tests/file.c)

# includes 'tree.c', so we either need to re-define '-Dav_export_libavutil=' (empty)
# or silence the warning. Let's silence, because the test does pass.
if ($c.target.class == 'windows')
{
  switch $c.id: path.match
  {
    case 'msvc'
      tests/obje{tree}: c.coptions += -wd4273
    case '*clang*'
      tests/obje{tree}: c.coptions += -Wno-inconsistent-dllimport
  }
}
