import avutil = libavutil%lib{avutil}
import libs = \
  libavutil%lib{avutil} \
  libavutil%lib{config}

# these tests are not run by upstream (ran with 'make fate -j 1 | grep libavutil')
# -utf8 -rational
for t : tests/c{* -lzo -utf8 -rational -pixelutils}
{
  c = $($avutil: libavutil.$name($t))
  ./: exe{$name($t)}: $t $libs testscript: include = ($c == [null] || $c)
}

# SET ARGS HERE FOR EACH EXE WHEN EXECUTED BY TESTSCRIPT. SEE libavutil.mak

c.poptions += -D_USE_MATH_DEFINES
# exe{lzo}: tests/c{lzo}: include = ($c.find_system_header("lzo/lzo1x.h") != [null])
