import config = libconfig%lib{config}
import libs = \
  libavutil%lib{avutil} \
  $config

requirements = [string_set] \
  '{"pixelutils": "pixelutils"}'

# need upstream/tests/checkasm/ lib that conditionally builds the asm files.
for t : tests/c{*.c -lzo}
{
  n = [string] $name($t)
  e = [bool] true
  for str: [string_set] $requirements
  {
    pair = [json] $json.parse($str)
    k = [string] $member_name($pair)
    if ($k == $n)
    {
      s = [string] "$member_value($pair)"
      v = [strings] $regex.split($s, ' ', ' ')
      for r: [strings] ($v)
      {
        c = $($config: libavutil.$r)
        if($c != 1)
        {
          e = false
        }
      }
      if(!$e)
      {
        text "skip test: libavutil/tests/$n.$extension($t) \(requires: $s\)"
      }
    }
  }

  exe{test-$n}: $t $libs testscript
  {
    cwd = [path] $src_base/tests/
  }
  ./: exe{test-$n}: include = $e
}

# needs some (any) file as input
exe{test-utf8}: test.arguments = "$src_base/tests/file.c"
