import libs = \
  libavformat%lib{avformat} \
  libavutil%lib{config}

TESTPROGS = seek                                                        \
            url                                                         \
            seek_utils
#           async                                                       \

for t : tests/c{$TESTPROGS}
{
  ./: exe{$name($t)}: $t $libs
}
