import config = libconfig%lib{config}
import libs = \
  libswscale%lib{swscale} \
  $config

requirements = [string_set] \
  '{"colorspace":     ""}' \
  '{"floatimg_cmp":   ""}' \
  '{"pixdesc_query":  ""}' \
  '{"swscale":        ""}'

# NOTE: Disable tests/swscale.c for the time being, it's unbelievably 
#       slow (presumably when without correct optimization flags)
for t : tests/c{*.c -swscale}
{
  n = [string] $name($t)
  e = [bool] true
  for str: [string_set] $requirements
  {
    pair = [json] $json.parse($str)
    k = [string] $member_name($pair)
    if ($k == $n)
    {
      s = [string] "$member_value($pair)"
      v = [strings] $regex.split($s, ' ', ' ')
      for r: [strings] ($v)
      {
        c = $($config: libconfig.$r)
        if($c == [null] || !$c)
        {
          e = false
        }
      }
      if(!$e)
      {
        text "skip test: libswscale/tests/$n.$extension($t) \(requires: $s\)"
      }
    }
  }

  exe{test-$n}: $t $libs testscript
  {
    cwd = [path] $path.posix_representation($src_base/tests/)
  }
  ./: exe{test-$n}: include = $e
}

## Build options.
#
import [once] libconfig%buildfile{common-configs}
