import avutil = libavutil%lib{avutil}
import libs = \
  libavfilter%lib{avfilter} \
  libavutil%lib{config}

# need upstream/tests/checkasm/ lib that conditionally builds the asm files.
for t : tests/c{* -integral}
{
  c = $($avutil: libavutil.$name($t))
  ./: exe{$name($t)}: $t $libs testscript: include = ($c == [null] || $c)
}
