import avutil = libavutil%lib{avutil}
import libs = \
  libavfilter%lib{avfilter} \
  libavutil%lib{config}

# TESTPROGS = \
#   drawutils \
#   filtfmts \
#   formats \
#   integral

# TESTOBJS += dctref.c

for t : tests/c{*}
{
  c = $($avutil: libavutil.$name($t))
  ./: exe{$name($t)}: $t $libs testscript: include = ($c == [null] || $c)
}
