using autoconf

intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.

import config = libconfig%lib{config}
impl_libs += $config
import intf_libs += \
  libavutil%lib{avutil} \
  libavformat%lib{avformat}

cpu = [string] $c.target.cpu
tgt_win32 = [bool] ($c.target.system == 'win32-msvc')
tgt_macos = [bool] ($c.target.system == 'darwin')

lib{postproc}: libul{postproc}: \
                libpostproc/h{**} \
                $impl_libs $intf_libs

conditional_src  = $json.load($src_base/files.json)

# conditional source & assembly
import [once] libconfig%buildfile{conditional-src}
import [once] libconfig%buildfile{symbol-importation}
libul{postproc}: impl_target{symbol-importation}: libpostproc/h{**}
libua{postproc}: libpostproc/impl_target{conditional-asm-obja}: libpostproc/asm{**}
libus{postproc}: libpostproc/impl_target{conditional-asm-objs}: libpostproc/asm{**}
libul{postproc}: libpostproc/impl_target{conditional-src}: libpostproc/c{**}

# Build options.
#
import [once] libconfig%buildfile{common-configs}

out_pfx = [dir_path] $out_root/src/
src_pfx = [dir_path] $src_root/src/

c.poptions += "-I$out_pfx" "-I$src_pfx" "-I$src_pfx/libpostproc/" -DBUILDING_postproc -Dav_export_postproc=

# System libraries
sys_libs =
switch $c.target.class, $c.target.system
{
  case 'windows', 'win32-msvc'
    sys_libs += bcrypt.lib \
                gdi32.lib \
                mfuuid.lib \
                ole32.lib \
                oleaut32.lib \
                psapi.lib \
                secur32.lib \
                shell32.lib \
                shlwapi.lib \
                strmiids.lib \
                user32.lib \
                uuid.lib \
                vfw32.lib \
                ws2_32.lib
  case 'windows', 'mingw32'
    sys_libs += -lbcrypt
}
c.libs += $sys_libs

switch ($c.target.system)
{
  case 'win32-msvc'
  {
    c.coptions += -wd4018 -wd4146 -wd4244 -wd4305 -wd4554 -wd4133 -wd4333
    c.poptions += -DWIN32_LEAN_AND_MEAN -D_USE_MATH_DEFINES -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_WARNINGS
  }
}

libs{postproc}: def{postproc}: include = ($c.target.system == 'win32-msvc')
def{postproc}: libul{postproc}

if ($c.target.system == 'mingw32')
  c.loptions += -Wl,--export-all-symbols

# Export options.
#
lib{postproc}:
{
  c.export.poptions = "-I$out_pfx" "-I$src_pfx" -Dav_export_postproc=
  c.export.libs = $intf_libs $sys_libs
}

if ($c.target.system == 'win32-msvc')
{
  libs{postproc}:
  {
    c.export.poptions += -Dav_export_postproc=__declspec\(dllimport\)
  }
}

# For pre-releases use the complete version to make sure they cannot
# be used in place of another pre-release or the final version. See
# the version module for details on the version.* variable values.
#
if $version.pre_release
  lib{postproc}: bin.lib.version = "-$version.project_id"
else
  lib{postproc}: bin.lib.version = "-$version.major.$version.minor"

# Install recreating subdirectories.
#
h{*}:
{
  install         = include/
  install.subdirs = true
}
